# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4debc7851df50824022262dfc208386e60ec31a212d46f08159a2eccc18669bf1891168ef4f90c5ce6b21d72c09268c392a667eadff8894461d712d9d71e7b49

test:
  secret_key_base: 5896c9acc8688bc9709f3627198be725b1ad25c9bdc3aab48f0d9c34e9f52ee43189b27ae53ce9537cf5fb273ef3d5dcf9dd3011e39007f1a9fb7e4e07254dfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
